### ISSUE TITLE
Tombstones not properly deleted?

### ISSUE THREAD

**Issue by zhuowei** [feravolt/FeraDroid-Engine#1]
I noticed that https://github.com/feravolt/FeraDroid-Engine/blob/d2b379ba91cbf8bd3ec83f842d8ee4b2ae11e22a/system/engine/gears/001abc.sh#L44 wouldn't remove the tombstone files, which are named /data/tombstones/tombstone_(a number) without an extension (so not a .txt or .log file)

You might want to check if this script does remove tombstones. If it doesn't, you might want to change the line to `$B rm -f /data/tombstones/*`

**Comment by feravolt** [comment]
Thanks for pointing this. Fixed commit - https://github.com/feravolt/FeraDroid-Engine/commit/bb59be88f34ba317f1ab53caa6bdea2b010f34cf
